---

- name: Copy Oracle JDK
  copy: src=jdk-8u65-linux-x64.tar.gz dest=/home/vagrant/jdk-8u65-linux-x64.tar.gz

- name: Copy Oracle JDK installation script
  copy: src=install-oracle-jdk.sh dest=/home/vagrant/install-oracle-jdk.sh

- name: Run Oracle JDK installation script
  command: chdir=/home/vagrant bash install-oracle-jdk.sh

- name: Install required packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - libboost-all-dev
    - libgmp3-dev
    - gcc
    - g++

- name: Creating domjudge-run user
  user: name=domjudge-run group=nogroup shell=/bin/false home=/nonexistent

- name: Configure DOMjudge
  command: chdir={{domjudge_folder}}/domjudge-{{domjudge_version}} ./configure --prefix={{domjudge_folder}}
  sudo_user: domjudge

- name: Build judgehost
  command: chdir={{domjudge_folder}}/domjudge-{{domjudge_version}} make judgehost
  sudo_user: domjudge

- name: Install judgehost
  command: chdir={{domjudge_folder}}/domjudge-{{domjudge_version}} make install-judgehost

- name: Copy sudoers file for judgedaemon
  command: cp {{domjudge_folder}}/judgehost/etc/sudoers-domjudge /etc/sudoers.d

- name: Copy judgehost config that disables CHROOT
  template: src=templates/judgehost/judgehost-config.php dest={{domjudge_folder}}/judgehost/etc/judgehost-config.php

- name: Copy judgehost Upstart script
  template: src=templates/judgehost/judgehost.upstart.conf dest=/etc/init/judgehost.conf

- name: Reload Upstart configuration
  command: initctl reload-configuration

- name: Start judgehost daemon
  service: name=judgehost state=started


